apiVersion: v1
items:
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      annotations:
        deployment.kubernetes.io/revision: "4"
      creationTimestamp: null
      generation: 1
      labels:
        run: blockexplorer
      name: blockexplorer
      selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/blockexplorer
    spec:
      progressDeadlineSeconds: 600
      replicas: 1
      revisionHistoryLimit: 10
      selector:
        matchLabels:
          run: blockexplorer
      strategy:
        rollingUpdate:
          maxSurge: 25%
          maxUnavailable: 25%
        type: RollingUpdate
      template:
        metadata:
          creationTimestamp: null
          labels:
            run: blockexplorer
        spec:
          containers:
            - envFrom:
                - configMapRef:
                    name: java-opt-k8s
              image: hongsgo/blockchainexplorer:latest
              imagePullPolicy: Always
              name: blockexplorer
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
    status: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""