apiVersion: skaffold/v1beta12
kind: Config
build:
  artifacts:
    - image: hongsgo/blockchain-monitor
      context: .
      jibGradle:
        project: api
deploy:
  kubectl:
    manifests:
      - api/deployment.yaml