apiVersion: v1
kind: Service
metadata:
  name: blockexplorer-dev
  labels:
    app: blockexplorer-dev
spec:
  ports:
    - port: 8080
      nodePort: 32764
  type: NodePort
  selector:
    app: blockexplorer-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockexplorer-dev
  labels:
    app: blockexplorer-dev
spec:
  selector:
    matchLabels:
      app: blockexplorer-dev
  template:
    metadata:
      labels:
        app: blockexplorer-dev
    spec:
      containers:
        - name: blockexplorer-dev
          image: hongsgo/blockexplorer
          ports:
            - containerPort: 3000
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health/check
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          envFrom:
            - configMapRef:
                name: spring-boot-dev
